name: mastermind

services:
  mastermind-php-fpm:
    container_name: mastermind-php-fpm
    build:
      context: .
      dockerfile: .docker/local/Dockerfile
    volumes:
      - ./:/var/www/myapp/
    env_file:
      - .env.local
    restart: unless-stopped
    ports:
      - "8081:80"
    depends_on:
      - mastermind-postgres
    networks:
      mastermind:
      nginx-proxy-manager_default:

  mastermind-postgres:
    container_name: mastermind-postgres
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    env_file:
      - .env.local
    restart: unless-stopped
    ports:
      - "5432"
    networks:
      mastermind:
      jump-server:

networks:
  mastermind:
    name: mastermind
  nginx-proxy-manager_default:
    external: true
  jump-server:
    external: true
