[supervisord]
nodaemon=true

[program:php8.3-fpm]
command=/usr/sbin/php-fpm8.3
autostart=true
autorestart=true
priority=900

# [program:messanger-worker]
# command=php bin/console messenger:consume async -vv
# autostart=true
# autorestart=true
# user=www-data

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
priority=800